version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html

  mysql:
    image: mariadb:11.0.2
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
      MYSQL_USER: levi
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
